"""Purchased-precursor constants (CBAM SEE E_PurchPrec)."""

from __future__ import annotations

from typing import Final

METHODOLOGY_CODE = 'PURCHASED_PRECURSOR_V1'
METHODOLOGY_VERSION = '1.0.0'

WORKBOOK_FILENAME = (
    'CBAM SEE V2.1_Example Steel 3 Screws and nuts_final '
    'Dosyasının Kopyası- (1) (1).xlsx'
)
WORKBOOK_SHA256 = '83170fde547c418dcae7f6a32852555d6874e092769f387b263108a231b2dd64'
WORKBOOK_PRIMARY_SHEET = 'E_PurchPrec'

# Precursor 1 template block (E_PurchPrec).
WORKBOOK_FORMULA_REFS = (
    'L25=SUM(production-route amounts); '
    'L39=L25-SUM(L28:L38); '
    'L52=L50*L51; '
    'T49=L25*L49; '
    'T52=L25*L52'
)

# Data-source modes. Phase 10A V1 activates the two primary modes only; the
# workbook Measured/Default/Unknown per-parameter switches are exposed as a
# controlled list but never mixed inside one precursor record.
MODE_SUPPLIER_DATA = 'SUPPLIER_DATA'
MODE_EU_DEFAULT = 'EU_DEFAULT'
SUPPORTED_DATA_SOURCE_MODES: Final[frozenset[str]] = frozenset(
    {MODE_SUPPLIER_DATA, MODE_EU_DEFAULT}
)

PRECURSOR_STATUS_DRAFT = 'draft'
PRECURSOR_STATUS_ARCHIVED = 'archived'
PRECURSOR_LIFECYCLE_STATUSES: Final[frozenset[str]] = frozenset(
    {PRECURSOR_STATUS_DRAFT, PRECURSOR_STATUS_ARCHIVED}
)

READINESS_EMPTY = 'EMPTY'
READINESS_INCOMPLETE = 'INCOMPLETE'
READINESS_UNBALANCED = 'UNBALANCED'
READINESS_UNRESOLVED = 'UNRESOLVED'
READINESS_AMBIGUOUS = 'AMBIGUOUS'
READINESS_READY = 'READY'

BALANCE_BALANCED = 'BALANCED'
BALANCE_UNBALANCED = 'UNBALANCED'
BALANCE_INCOMPLETE = 'INCOMPLETE'

RESOLUTION_RESOLVED = 'RESOLVED'
RESOLUTION_UNRESOLVED = 'UNRESOLVED'
RESOLUTION_AMBIGUOUS = 'AMBIGUOUS'
RESOLUTION_NOT_APPLICABLE = 'NOT_APPLICABLE'

CALC_STATUS_CALCULATED = 'CALCULATED'
CALC_STATUS_INCOMPLETE = 'INCOMPLETE'
CALC_STATUS_NOT_CALCULATED = 'NOT_CALCULATED'

# Blocking / validation codes (server-authoritative).
CODE_PRECURSOR_NAME_REQUIRED = 'PRECURSOR_NAME_REQUIRED'
CODE_PRECURSOR_CN_REQUIRED = 'PRECURSOR_CN_CODE_REQUIRED'
CODE_PRECURSOR_CN_CODE_REQUIRED = CODE_PRECURSOR_CN_REQUIRED
CODE_PRECURSOR_COUNTRY_REQUIRED = 'PRECURSOR_COUNTRY_REQUIRED'
CODE_PRECURSOR_ROUTE_REQUIRED = 'PRECURSOR_ROUTE_REQUIRED'
CODE_PRECURSOR_QUANTITY_REQUIRED = 'PRECURSOR_QUANTITY_REQUIRED'
CODE_PRECURSOR_QUANTITY_MISSING = CODE_PRECURSOR_QUANTITY_REQUIRED
CODE_PRECURSOR_DISTRIBUTION_INCOMPLETE = 'PRECURSOR_DISTRIBUTION_INCOMPLETE'
CODE_PRECURSOR_DISTRIBUTION_UNBALANCED = 'PRECURSOR_DISTRIBUTION_UNBALANCED'
CODE_PRECURSOR_ARCHIVED = 'PRECURSOR_ARCHIVED'
CODE_PRECURSOR_MODE_REQUIRED = 'PRECURSOR_MODE_REQUIRED'
CODE_PRECURSOR_MODE_UNSUPPORTED = 'PRECURSOR_MODE_UNSUPPORTED'
CODE_TARGET_PRODUCT_INVALID = 'PRECURSOR_TARGET_PRODUCT_INVALID'
CODE_PRECURSOR_TARGET_PRODUCT_INVALID = CODE_TARGET_PRODUCT_INVALID
CODE_INCOMPATIBLE_PRECURSOR_UNIT = 'INCOMPATIBLE_PRECURSOR_UNIT'
CODE_INCOMPATIBLE_MASS_UNIT = CODE_INCOMPATIBLE_PRECURSOR_UNIT
CODE_SUPPLIER_EMISSIONS_DATA_REQUIRED = 'SUPPLIER_EMISSIONS_DATA_REQUIRED'
CODE_SUPPLIER_DIRECT_EMISSIONS_MISSING = CODE_SUPPLIER_EMISSIONS_DATA_REQUIRED
CODE_SUPPLIER_ELECTRICITY_DATA_INCOMPLETE = CODE_SUPPLIER_EMISSIONS_DATA_REQUIRED
CODE_SUPPLIER_PROVENANCE_REQUIRED = 'SUPPLIER_PROVENANCE_REQUIRED'
CODE_DEFAULT_VALUE_UNRESOLVED = 'DEFAULT_VALUE_UNRESOLVED'
CODE_DEFAULT_VALUE_AMBIGUOUS = 'DEFAULT_VALUE_AMBIGUOUS'
CODE_DEFAULT_VALUE_NOT_NUMERIC = 'DEFAULT_VALUE_NOT_NUMERIC'
CODE_MIXED_PRECURSOR_SOURCE_NOT_SUPPORTED = 'MIXED_PRECURSOR_SOURCE_NOT_SUPPORTED'
CODE_PURCHASED_INPUT_INVALID = 'PURCHASED_INPUT_INVALID'
CODE_SUPPLIER_INVALID = 'SUPPLIER_INVALID'
CODE_JUSTIFICATION_CODE_INVALID = 'JUSTIFICATION_CODE_INVALID'
CODE_ELECTRICITY_SOURCE_CODE_INVALID = 'ELECTRICITY_SOURCE_CODE_INVALID'
CODE_PARAMETER_SOURCE_CODE_INVALID = 'PARAMETER_SOURCE_CODE_INVALID'

# EU default-value catalog (Implementing Regulation (EU) 2025/2621).
DEFAULT_DATASET_CODE = 'CBAM_EU_DEFAULT_VALUES'
DEFAULT_DATASET_VERSION = 'IR_2025_2621_v20260204'
DEFAULT_DATASET_STATUS_ACTIVE = 'ACTIVE'
OTHER_COUNTRIES_GROUP_NAME = 'Other Countries and Territories'
OTHER_COUNTRIES_FALLBACK_NOTE = (
    'The "Other Countries and Territories" group is never selected automatically. '
    'The declarant must pick it explicitly as the country of origin.'
)

# Numeric-vs-textual cell states carried over from the DV workbook.
DV_STATUS_NUMERIC = 'NUMERIC'
DV_STATUS_DASH = 'DASH'
DV_STATUS_NA = 'NA'
DV_STATUS_SEE_BELOW = 'SEE_BELOW'
DV_STATUS_BLANK = 'BLANK'
DV_STATUS_TEXT = 'TEXT'

LOOKUP_KEY_SEPARATOR = '|'
LOOKUP_KEY_MAX_LENGTH = 512

# SEE application units. The DV workbook itself does not label emission units;
# SEE applies specific embedded emissions per tonne of goods.
CANONICAL_MASS_UNIT = 't'
SPECIFIC_DIRECT_UNIT = 'tCO2e/t'
SPECIFIC_INDIRECT_UNIT = 'tCO2e/t'
ELECTRICITY_INTENSITY_UNIT = 'MWh/t'
ELECTRICITY_EF_UNIT = 'tCO2e/MWh'
RESULT_UNIT_TCO2E = 'tCO2e'

# Controlled lists (SEE Parameters_Constants named ranges).
MEAS_DEFAULT_UNKNOWN_LIST_CODE = 'CONST_MeasDefaultUnknown'
ELEC_SOURCE_LIST_CODE = 'CONST_ElecSource'
DEFAULT_JUSTIFICATION_LIST_CODE = 'CONST_DefaultJustification'

PARAMETER_SOURCE_MEASURED = 'MEASURED'
PARAMETER_SOURCE_DEFAULT = 'DEFAULT'
PARAMETER_SOURCE_UNKNOWN = 'UNKNOWN'

PRODUCT_TOTALS_ROLLUP_NOTE = (
    'Phase 10A keeps purchased-precursor embedded emissions standalone. They are not '
    'rolled up into product totals or any allocation result.'
)
