"""Conventional production-process constants (CBAM SEE D_Processes)."""

from __future__ import annotations

from decimal import Decimal

METHODOLOGY_CODE = 'CONVENTIONAL_PRODUCTION_PROCESS_V1'
METHODOLOGY_VERSION = '1.0.0'

WORKBOOK_FILENAME = (
    'CBAM SEE V2.1_Example Steel 3 Screws and nuts_final '
    'Dosyasının Kopyası- (1) (1).xlsx'
)
WORKBOOK_SHA256 = '83170fde547c418dcae7f6a32852555d6874e092769f387b263108a231b2dd64'
WORKBOOK_PRIMARY_SHEET = 'D_Processes'

# Process 1 (template block starts at row 11; stride 65)
WORKBOOK_FORMULA_REFS = (
    'L24=SUM(L16:L23); '
    'L28=L27/L24; '
    'L29=AND(L24>0,L24=L27); '
    'L42=L24-(L27+SUM(L32:L41)); '
    'T58=L57*L58-M57*M58; '
    'T62=L61*CONST_EFNatGas-M61*CONST_EFNatGas*0.667; '
    'T66=L65*L66; '
    'T72=-L71*L72'
)

# Parameters_Constants!B13 — used by D_Processes!T62 (waste-gas attributed emissions)
CONST_EF_NAT_GAS_TCO2_PER_TJ = Decimal('56.1')
WASTE_GAS_EXPORT_FACTOR = Decimal('0.667')

METHOD_CONVENTIONAL = 'CONVENTIONAL'
METHOD_PROCESS_EMISSIONS = 'PROCESS_EMISSIONS'
METHOD_MASS_BALANCE = 'MASS_BALANCE'
SUPPORTED_CALCULATION_METHODS = frozenset({METHOD_CONVENTIONAL})
# Future / disabled — accepted as enum vocabulary only; create/patch reject them.
DISABLED_CALCULATION_METHODS = frozenset(
    {METHOD_PROCESS_EMISSIONS, METHOD_MASS_BALANCE}
)
ALL_CALCULATION_METHODS = SUPPORTED_CALCULATION_METHODS | DISABLED_CALCULATION_METHODS

PROCESS_STATUS_DRAFT = 'draft'
PROCESS_STATUS_ARCHIVED = 'archived'
PROCESS_LIFECYCLE_STATUSES = frozenset({PROCESS_STATUS_DRAFT, PROCESS_STATUS_ARCHIVED})

READINESS_EMPTY = 'EMPTY'
READINESS_INCOMPLETE = 'INCOMPLETE'
READINESS_UNBALANCED = 'UNBALANCED'
READINESS_STALE = 'STALE'
READINESS_READY = 'READY'

BALANCE_BALANCED = 'BALANCED'
BALANCE_UNBALANCED = 'UNBALANCED'
BALANCE_INCOMPLETE = 'INCOMPLETE'

HEAT_CALC_STATUS_CALCULATED = 'CALCULATED'
HEAT_CALC_STATUS_NOT_APPLICABLE = 'NOT_APPLICABLE'
HEAT_CALC_STATUS_INCOMPLETE = 'INCOMPLETE'
HEAT_CALC_STATUS_NOT_CALCULATED = 'NOT_CALCULATED'

WASTE_GAS_CALC_STATUS_CALCULATED = 'CALCULATED'
WASTE_GAS_CALC_STATUS_NOT_APPLICABLE = 'NOT_APPLICABLE'
WASTE_GAS_CALC_STATUS_INCOMPLETE = 'INCOMPLETE'
WASTE_GAS_CALC_STATUS_NOT_CALCULATED = 'NOT_CALCULATED'

# Process-level exported electricity (workbook D_Processes!T72 = -L71*L72).
EXPORTED_ELECTRICITY_CALC_STATUS_CALCULATED = 'CALCULATED'
EXPORTED_ELECTRICITY_CALC_STATUS_NOT_APPLICABLE = 'NOT_APPLICABLE'
EXPORTED_ELECTRICITY_CALC_STATUS_INCOMPLETE = 'INCOMPLETE'

EXPORTED_ELECTRICITY_QUANTITY_UNIT = 'MWh'
EXPORTED_ELECTRICITY_FACTOR_UNIT = 'tCO2/MWh'
EXPORTED_ELECTRICITY_FORMULA_REF = 'D_Processes!T72=-L71*L72'

# Reconciliation between process-level L71 entries and facility purchased-electricity
# export results. EcoTrace never copies one into the other and never divides a facility
# total across processes.
EXPORTED_ELECTRICITY_RECONCILIATION_NOT_APPLICABLE = 'NOT_APPLICABLE'
EXPORTED_ELECTRICITY_RECONCILIATION_NOT_COMPARABLE = 'NOT_COMPARABLE'
EXPORTED_ELECTRICITY_RECONCILIATION_MATCHED = 'MATCHED'
EXPORTED_ELECTRICITY_RECONCILIATION_MISMATCHED = 'MISMATCHED'
EXPORTED_ELECTRICITY_RECONCILIATION_NOTE = (
    'Process-level exported electricity (D_Processes!L71) and facility purchased-electricity '
    'export results are independent entries. EcoTrace compares the installation totals and '
    'reports the difference; it never copies the facility value into a process and never '
    'divides a facility total across processes.'
)

# Blocking codes (server-authoritative readiness)
CODE_PROCESS_PRODUCT_REQUIRED = 'PROCESS_PRODUCT_REQUIRED'
CODE_PROCESS_METHOD_REQUIRED = 'PROCESS_METHOD_REQUIRED'
CODE_PROCESS_METHOD_UNSUPPORTED = 'PROCESS_METHOD_UNSUPPORTED'
CODE_PROCESS_NAME_REQUIRED = 'PROCESS_NAME_REQUIRED'
CODE_PRODUCTION_QUANTITY_MISSING = 'PRODUCTION_QUANTITY_MISSING'
CODE_PRODUCT_DISTRIBUTION_INCOMPLETE = 'PRODUCT_DISTRIBUTION_INCOMPLETE'
CODE_PRODUCT_DISTRIBUTION_UNBALANCED = 'PRODUCT_DISTRIBUTION_UNBALANCED'
CODE_TARGET_PRODUCT_INVALID = 'TARGET_PRODUCT_INVALID'
CODE_DIRECT_EMISSIONS_ALLOCATION_NOT_READY = 'DIRECT_EMISSIONS_ALLOCATION_NOT_READY'
CODE_INDIRECT_EMISSIONS_ALLOCATION_NOT_READY = 'INDIRECT_EMISSIONS_ALLOCATION_NOT_READY'
CODE_INDIRECT_EMISSIONS_PRODUCT_ALLOCATION_MISSING = (
    'INDIRECT_EMISSIONS_PRODUCT_ALLOCATION_MISSING'
)
CODE_MEASURABLE_HEAT_DATA_INCOMPLETE = 'MEASURABLE_HEAT_DATA_INCOMPLETE'
CODE_WASTE_GAS_DATA_INCOMPLETE = 'WASTE_GAS_DATA_INCOMPLETE'
CODE_DATA_QUALITY_ANSWER_REQUIRED = 'DATA_QUALITY_ANSWER_REQUIRED'
CODE_DATA_QUALITY_CODE_INVALID = 'DATA_QUALITY_CODE_INVALID'
CODE_HEAT_FIELDS_NOT_ALLOWED = 'HEAT_FIELDS_NOT_ALLOWED'
CODE_WASTE_GAS_FIELDS_NOT_ALLOWED = 'WASTE_GAS_FIELDS_NOT_ALLOWED'
CODE_INCOMPATIBLE_MASS_UNIT = 'INCOMPATIBLE_MASS_UNIT'
CODE_PROCESS_ARCHIVED = 'PROCESS_ARCHIVED'
CODE_EXPORTED_ELECTRICITY_DATA_INCOMPLETE = 'EXPORTED_ELECTRICITY_DATA_INCOMPLETE'
CODE_EXPORTED_ELECTRICITY_FACTOR_REQUIRED = 'EXPORTED_ELECTRICITY_FACTOR_REQUIRED'
CODE_EXPORTED_ELECTRICITY_PROVENANCE_REQUIRED = 'EXPORTED_ELECTRICITY_PROVENANCE_REQUIRED'
CODE_EXPORTED_ELECTRICITY_RECONCILIATION_MISMATCH = (
    'EXPORTED_ELECTRICITY_RECONCILIATION_MISMATCH'
)
CODE_EXPORTED_ELECTRICITY_FIELDS_NOT_ALLOWED = 'EXPORTED_ELECTRICITY_FIELDS_NOT_ALLOWED'

CANONICAL_MASS_UNIT = 't'
HEAT_QUANTITY_UNIT = 'TJ'
HEAT_FACTOR_UNIT = 'tCO2/TJ'
WASTE_GAS_QUANTITY_UNIT = 'TJ'
RESULT_UNIT_TCO2 = 'tCO2'
RESULT_UNIT_TCO2E = 'tCO2e'
ELECTRICITY_UNIT_MWH = 'MWh'

# Data-quality lists live on C_Emissions&Energy (CONST_DataQuality*), not D_Processes.
# Optional on process drafts; exposed for FE typed dropdowns.
DATA_QUALITY_LIST_CODE = 'CONST_DataQuality'
DATA_VERIFICATION_LIST_CODE = 'CONST_DataVerification'
DATA_QUALITY_JUSTIFICATION_LIST_CODE = 'CONST_DataQualityJustification'
ELEC_EF_SOURCE_LIST_CODE = 'CONST_ElecSource'
MONITORING_APPROACH_LIST_CODE = 'CONST_MonitoringApproach'

PRODUCTION_QUANTITY_SOURCE = 'PROCESS_EXPLICIT'
PRODUCTION_QUANTITY_SOURCE_NOTE = (
    'SEE D_Processes L16:L23→L24 are process-block inputs distinct from EcoTrace '
    'cbam_production_records. Process produced_quantity is persisted explicitly; '
    'production-record totals are exposed for reconciliation only and never overwrite '
    'either source.'
)
