from typing import Final
TREND_INCREASED: Final[str] = 'increased'
TREND_DECREASED: Final[str] = 'decreased'
TREND_UNCHANGED: Final[str] = 'unchanged'
TREND_UNAVAILABLE: Final[str] = 'unavailable'
AVAIL_AVAILABLE: Final[str] = 'available'
AVAIL_UNAVAILABLE: Final[str] = 'unavailable'
BASELINE_CARBON: Final[str] = 'carbon_inventory'
BASELINE_INTENSITY: Final[str] = 'intensity'
BASELINE_KPI: Final[str] = 'environmental_kpi'
BASELINE_STATUSES: Final[frozenset[str]] = frozenset({'draft', 'approved', 'archived'})
TARGET_TYPES: Final[frozenset[str]] = frozenset({'absolute_emission_reduction', 'intensity_reduction', 'renewable_energy_share', 'energy_reduction', 'water_reduction', 'waste_reduction', 'recycling_increase'})
TARGET_STATUSES: Final[frozenset[str]] = frozenset({'draft', 'active', 'achieved', 'missed', 'cancelled', 'archived'})
TARGET_DIRECTIONS: Final[frozenset[str]] = frozenset({'decrease', 'increase', 'maintain'})
PROGRESS_NOT_STARTED: Final[str] = 'not_started'
PROGRESS_ON_TRACK: Final[str] = 'on_track'
PROGRESS_AT_RISK: Final[str] = 'at_risk'
PROGRESS_OFF_TRACK: Final[str] = 'off_track'
PROGRESS_ACHIEVED: Final[str] = 'achieved'
PROGRESS_MISSED: Final[str] = 'missed'
PROGRESS_UNAVAILABLE: Final[str] = 'unavailable'
PROGRESS_AT_RISK_TOLERANCE: Final[str] = '0.10'
INITIATIVE_TYPES: Final[frozenset[str]] = frozenset({'renewable_energy', 'energy_efficiency', 'fuel_switching', 'fleet_optimization', 'logistics_optimization', 'waste_reduction', 'recycling', 'water_efficiency', 'equipment_replacement', 'process_improvement', 'behavioral_change', 'other'})
INITIATIVE_STATUSES: Final[frozenset[str]] = frozenset({'proposed', 'approved', 'planned', 'in_progress', 'completed', 'cancelled', 'archived'})
INITIATIVE_TRANSITIONS: Final[dict[str, frozenset[str]]] = {'proposed': frozenset({'approved', 'cancelled'}), 'approved': frozenset({'planned', 'cancelled'}), 'planned': frozenset({'in_progress', 'cancelled'}), 'in_progress': frozenset({'completed', 'cancelled'}), 'completed': frozenset({'archived'}), 'cancelled': frozenset({'archived'}), 'archived': frozenset()}
SCENARIO_TYPES: Final[frozenset[str]] = frozenset({'renewable_energy_transition', 'electricity_reduction', 'natural_gas_reduction', 'fuel_switch', 'fleet_efficiency', 'transport_mode_shift', 'waste_reduction', 'recycling_improvement', 'production_efficiency', 'custom_activity_adjustment'})
SCENARIO_STATUSES: Final[frozenset[str]] = frozenset({'draft', 'ready', 'calculated', 'archived'})
NUMERATOR_TYPES: Final[frozenset[str]] = frozenset({'total_emissions', 'scope_1', 'scope_2', 'scope_3', 'selected_category'})
KPI_TYPES: Final[frozenset[str]] = frozenset({'energy_consumption', 'renewable_energy_share', 'water_consumption', 'wastewater_volume', 'hazardous_waste', 'non_hazardous_waste', 'recycled_waste', 'production_output', 'total_emissions', 'carbon_intensity'})
REC_PRIORITY: Final[frozenset[str]] = frozenset({'low', 'medium', 'high', 'critical'})
