from typing import Final
REPAIRABILITY_SCALE_MIN: Final[int] = 1
REPAIRABILITY_SCALE_MAX: Final[int] = 10
SUSTAINABILITY_RATING_MIN: Final[int] = 1
SUSTAINABILITY_RATING_MAX: Final[int] = 5
DATA_QUALITY_MIN: Final[int] = 1
DATA_QUALITY_MAX: Final[int] = 5
PRODUCT_TYPES: Final[frozenset[str]] = frozenset({'finished_good', 'intermediate_good', 'component', 'service', 'packaging', 'co_product', 'other'})
BATCH_STATUSES: Final[frozenset[str]] = frozenset({'planned', 'in_production', 'completed', 'released', 'recalled', 'archived'})
BATCH_TRANSITIONS: Final[dict[str, frozenset[str]]] = {'planned': frozenset({'in_production', 'archived'}), 'in_production': frozenset({'completed', 'archived'}), 'completed': frozenset({'released', 'recalled'}), 'released': frozenset({'recalled', 'archived'}), 'recalled': frozenset({'archived'}), 'archived': frozenset()}
SUPPLIER_TYPES: Final[frozenset[str]] = frozenset({'raw_material', 'component', 'packaging', 'logistics', 'service', 'other'})
SUPPLIER_STATUSES: Final[frozenset[str]] = frozenset({'draft', 'active', 'suspended', 'archived'})
MATERIAL_CATEGORIES: Final[frozenset[str]] = frozenset({'metal', 'plastic', 'glass', 'paper', 'cardboard', 'textile', 'chemical', 'biological', 'agricultural', 'electronic', 'packaging', 'energy_carrier', 'water', 'other'})
BOM_STATUSES: Final[frozenset[str]] = frozenset({'draft', 'under_review', 'approved', 'superseded', 'archived'})
LCA_STUDY_TYPES: Final[frozenset[str]] = frozenset({'cradle_to_gate', 'cradle_to_grave', 'cradle_to_cradle', 'gate_to_gate', 'screening_lca', 'product_carbon_footprint'})
LCA_STUDY_STATUSES: Final[frozenset[str]] = frozenset({'draft', 'data_collection', 'ready_for_calculation', 'calculated', 'under_review', 'approved', 'superseded', 'archived'})
LCA_STUDY_TRANSITIONS: Final[dict[str, frozenset[str]]] = {'draft': frozenset({'data_collection', 'archived'}), 'data_collection': frozenset({'ready_for_calculation', 'draft', 'archived'}), 'ready_for_calculation': frozenset({'calculated', 'data_collection'}), 'calculated': frozenset({'under_review', 'ready_for_calculation'}), 'under_review': frozenset({'approved', 'calculated'}), 'approved': frozenset({'superseded', 'archived'}), 'superseded': frozenset({'archived'}), 'archived': frozenset()}
LIFECYCLE_STAGES: Final[frozenset[str]] = frozenset({'raw_material_extraction', 'material_processing', 'inbound_transport', 'manufacturing', 'packaging', 'distribution', 'use_phase', 'maintenance', 'repair', 'reuse', 'recycling', 'end_of_life', 'waste_treatment'})
CRADLE_TO_GATE_STAGES: Final[frozenset[str]] = frozenset({'raw_material_extraction', 'material_processing', 'inbound_transport', 'manufacturing', 'packaging'})
USE_PHASE_STAGES: Final[frozenset[str]] = frozenset({'use_phase', 'maintenance', 'repair'})
END_OF_LIFE_STAGES: Final[frozenset[str]] = frozenset({'reuse', 'recycling', 'end_of_life', 'waste_treatment'})
INPUT_TYPES: Final[frozenset[str]] = frozenset({'material', 'component', 'energy', 'fuel', 'water', 'transport', 'waste', 'packaging', 'process_emission', 'use_phase_activity', 'end_of_life_activity', 'other'})
SOURCE_TYPES: Final[frozenset[str]] = frozenset({'measured', 'supplier_specific', 'organization_average', 'database', 'industry_average', 'estimated', 'proxy'})
ALLOCATION_METHODS: Final[frozenset[str]] = frozenset({'mass', 'energy', 'economic', 'physical', 'custom', 'none'})
PCF_STATUSES: Final[frozenset[str]] = frozenset({'draft', 'calculated', 'under_review', 'approved', 'superseded'})
PASSPORT_STATUSES: Final[frozenset[str]] = frozenset({'draft', 'under_review', 'published', 'revoked', 'superseded', 'archived'})
PASSPORT_TRANSITIONS: Final[dict[str, frozenset[str]]] = {'draft': frozenset({'under_review', 'archived'}), 'under_review': frozenset({'published', 'draft'}), 'published': frozenset({'revoked', 'superseded'}), 'revoked': frozenset({'archived'}), 'superseded': frozenset({'archived'}), 'archived': frozenset()}
PASSPORT_SECTIONS: Final[frozenset[str]] = frozenset({'product_identity', 'manufacturer', 'origin', 'composition', 'materials', 'recycled_content', 'carbon_footprint', 'lifecycle_stages', 'repairability', 'durability', 'recyclability', 'hazardous_substances', 'certifications', 'usage_instructions', 'maintenance', 'end_of_life', 'traceability', 'documents'})
PASSPORT_DOC_TYPES: Final[frozenset[str]] = frozenset({'specification', 'safety_data_sheet', 'declaration', 'test_report', 'repair_manual', 'recycling_guide', 'user_manual', 'certificate_reference', 'other'})
LCA_ENGINE_VERSION: Final[str] = 'ecotrace-lca-0.5.0'
LCA_METHODOLOGY_VERSION: Final[str] = 'iso14040-inspired-demo-0.5'
DISCLAIMER: Final[str] = 'Prototype / methodology-informed estimate only. Not certified ISO, PEF, EPD, ESRS, or CBAM compliance.'
