from __future__ import annotations
from collections.abc import Sequence
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0006_ai'
down_revision: str | None = '0005_lca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def _ts() -> tuple[object, object]:
    return (sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

def upgrade() -> None:
    ts = _ts()
    op.execute("DO $$ BEGIN CREATE EXTENSION IF NOT EXISTS vector; EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'vector extension unavailable; continuing with JSONB embeddings'; END $$;")
    op.execute("DO $$ BEGIN CREATE EXTENSION IF NOT EXISTS pg_trgm; EXCEPTION WHEN OTHERS THEN RAISE NOTICE 'pg_trgm extension unavailable'; END $$;")
    op.create_table('knowledge_documents', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('title', sa.String(512), nullable=False), sa.Column('slug', sa.String(255), nullable=False), sa.Column('document_type', sa.String(64), nullable=False), sa.Column('status', sa.String(32), nullable=False), sa.Column('language_code', sa.String(8), nullable=False), sa.Column('source_system', sa.String(64), nullable=True), sa.Column('source_record_type', sa.String(64), nullable=True), sa.Column('source_record_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True), sa.Column('permissions_json', postgresql.JSONB(), nullable=True), sa.Column('metadata_json', postgresql.JSONB(), nullable=True), sa.Column('current_version_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('created_by_user_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('published_at', sa.DateTime(timezone=True), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id', name='pk_knowledge_documents'), sa.UniqueConstraint('organization_id', 'slug', name='uq_knowledge_documents_org_slug'))
    op.create_index('ix_knowledge_documents_organization_id', 'knowledge_documents', ['organization_id'])
    op.create_index('ix_knowledge_documents_status', 'knowledge_documents', ['status'])
    op.create_index('ix_knowledge_documents_document_type', 'knowledge_documents', ['document_type'])
    op.create_index('ix_knowledge_documents_language', 'knowledge_documents', ['language_code'])
    op.create_table('knowledge_document_versions', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('version_number', sa.Integer(), nullable=False), sa.Column('status', sa.String(32), nullable=False), sa.Column('file_name', sa.String(512), nullable=False), sa.Column('content_type', sa.String(128), nullable=False), sa.Column('storage_path', sa.String(1024), nullable=False), sa.Column('checksum_sha256', sa.String(64), nullable=False), sa.Column('byte_size', sa.Integer(), nullable=False), sa.Column('extracted_text', sa.Text(), nullable=True), sa.Column('page_count', sa.Integer(), nullable=True), sa.Column('language_code', sa.String(8), nullable=False), sa.Column('processing_status', sa.String(32), nullable=False), sa.Column('processing_error', sa.Text(), nullable=True), sa.Column('quality_score', sa.Float(), nullable=True), sa.Column('supersedes_version_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('created_by_user_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('published_at', sa.DateTime(timezone=True), nullable=True), *ts, sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['supersedes_version_id'], ['knowledge_document_versions.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id', name='pk_knowledge_document_versions'), sa.UniqueConstraint('document_id', 'version_number', name='uq_knowledge_doc_version'))
    op.create_index('ix_knowledge_document_versions_document_id', 'knowledge_document_versions', ['document_id'])
    op.create_index('ix_knowledge_document_versions_status', 'knowledge_document_versions', ['status'])
    op.create_table('knowledge_chunks', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('document_version_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('chunk_index', sa.Integer(), nullable=False), sa.Column('content', sa.Text(), nullable=False), sa.Column('content_hash', sa.String(64), nullable=False), sa.Column('token_estimate', sa.Integer(), nullable=False), sa.Column('page_number', sa.Integer(), nullable=True), sa.Column('section_title', sa.String(512), nullable=True), sa.Column('language_code', sa.String(8), nullable=False), sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True), sa.Column('permissions_json', postgresql.JSONB(), nullable=True), sa.Column('metadata_json', postgresql.JSONB(), nullable=True), sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['document_version_id'], ['knowledge_document_versions.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id', name='pk_knowledge_chunks'), sa.UniqueConstraint('document_version_id', 'chunk_index', name='uq_knowledge_chunks_version_index'))
    op.create_index('ix_knowledge_chunks_organization_id', 'knowledge_chunks', ['organization_id'])
    op.create_index('ix_knowledge_chunks_document_id', 'knowledge_chunks', ['document_id'])
    op.create_index('ix_knowledge_chunks_document_version_id', 'knowledge_chunks', ['document_version_id'])
    op.create_index('ix_knowledge_chunks_language', 'knowledge_chunks', ['language_code'])
    op.create_index('ix_knowledge_chunks_content_hash', 'knowledge_chunks', ['content_hash'])
    op.execute('\n        DO $$\n        BEGIN\n            CREATE INDEX IF NOT EXISTS ix_knowledge_chunks_content_trgm\n            ON knowledge_chunks USING gin (content gin_trgm_ops);\n        EXCEPTION\n            WHEN undefined_object THEN\n                NULL;\n            WHEN feature_not_supported THEN\n                NULL;\n        END $$;\n        ')
    op.create_table('knowledge_embeddings', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('chunk_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('provider', sa.String(64), nullable=False), sa.Column('model_name', sa.String(128), nullable=False), sa.Column('dimensions', sa.Integer(), nullable=False), sa.Column('vector_json', postgresql.JSONB(), nullable=False), sa.Column('permissions_json', postgresql.JSONB(), nullable=True), sa.Column('metadata_json', postgresql.JSONB(), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id', name='pk_knowledge_embeddings'), sa.UniqueConstraint('chunk_id', 'model_name', name='uq_knowledge_embeddings_chunk_model'))
    op.create_index('ix_knowledge_embeddings_organization_id', 'knowledge_embeddings', ['organization_id'])
    op.create_index('ix_knowledge_embeddings_chunk_id', 'knowledge_embeddings', ['chunk_id'])
    op.create_index('ix_knowledge_embeddings_model_name', 'knowledge_embeddings', ['model_name'])
    op.create_table('chat_folders', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('owner_user_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('name', sa.String(255), nullable=False), sa.Column('parent_folder_id', postgresql.UUID(as_uuid=True), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['parent_folder_id'], ['chat_folders.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id', name='pk_chat_folders'), sa.UniqueConstraint('organization_id', 'owner_user_id', 'name', name='uq_chat_folders_owner_name'))
    op.create_index('ix_chat_folders_organization_id', 'chat_folders', ['organization_id'])
    op.create_index('ix_chat_folders_owner_user_id', 'chat_folders', ['owner_user_id'])
    op.create_table('chat_conversations', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('owner_user_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('folder_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('title', sa.String(255), nullable=False), sa.Column('status', sa.String(32), nullable=False), sa.Column('language_code', sa.String(8), nullable=False), sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False), sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False), sa.Column('is_shared_org', sa.Boolean(), server_default='false', nullable=False), sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True), sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True), sa.Column('memory_json', postgresql.JSONB(), nullable=True), sa.Column('metadata_json', postgresql.JSONB(), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['folder_id'], ['chat_folders.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id', name='pk_chat_conversations'))
    op.create_index('ix_chat_conversations_organization_id', 'chat_conversations', ['organization_id'])
    op.create_index('ix_chat_conversations_owner_user_id', 'chat_conversations', ['owner_user_id'])
    op.create_index('ix_chat_conversations_status', 'chat_conversations', ['status'])
    op.create_index('ix_chat_conversations_pinned', 'chat_conversations', ['is_pinned'])
    op.create_table('chat_messages', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('role', sa.String(32), nullable=False), sa.Column('content', sa.Text(), nullable=False), sa.Column('language_code', sa.String(8), nullable=False), sa.Column('citations_json', postgresql.JSONB(), nullable=True), sa.Column('confidence', sa.Float(), nullable=True), sa.Column('reasoning_json', postgresql.JSONB(), nullable=True), sa.Column('provider', sa.String(64), nullable=True), sa.Column('model_name', sa.String(128), nullable=True), sa.Column('prompt_tokens', sa.Integer(), nullable=True), sa.Column('completion_tokens', sa.Integer(), nullable=True), sa.Column('latency_ms', sa.Integer(), nullable=True), sa.Column('tool_calls_json', postgresql.JSONB(), nullable=True), sa.Column('metadata_json', postgresql.JSONB(), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id', name='pk_chat_messages'))
    op.create_index('ix_chat_messages_conversation_id', 'chat_messages', ['conversation_id'])
    op.create_index('ix_chat_messages_organization_id', 'chat_messages', ['organization_id'])
    op.create_index('ix_chat_messages_role', 'chat_messages', ['role'])
    op.create_table('prompt_templates', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('owner_user_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('code', sa.String(128), nullable=False), sa.Column('name', sa.String(255), nullable=False), sa.Column('scope', sa.String(32), nullable=False), sa.Column('version_number', sa.Integer(), nullable=False), sa.Column('template_body', sa.Text(), nullable=False), sa.Column('variables_json', postgresql.JSONB(), nullable=True), sa.Column('ab_group', sa.String(32), nullable=True), sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False), sa.Column('metadata_json', postgresql.JSONB(), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id', name='pk_prompt_templates'), sa.UniqueConstraint('organization_id', 'code', 'version_number', name='uq_prompt_templates_org_code_ver'))
    op.create_index('ix_prompt_templates_organization_id', 'prompt_templates', ['organization_id'])
    op.create_index('ix_prompt_templates_scope', 'prompt_templates', ['scope'])
    op.create_index('ix_prompt_templates_is_active', 'prompt_templates', ['is_active'])
    op.create_table('provider_configs', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('provider_kind', sa.String(32), nullable=False), sa.Column('provider_name', sa.String(64), nullable=False), sa.Column('model_name', sa.String(128), nullable=True), sa.Column('base_url', sa.String(512), nullable=True), sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False), sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False), sa.Column('config_json', postgresql.JSONB(), nullable=True), sa.Column('secret_ref', sa.String(255), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id', name='pk_provider_configs'), sa.UniqueConstraint('organization_id', 'provider_kind', 'provider_name', name='uq_provider_configs_org_kind'))
    op.create_index('ix_provider_configs_organization_id', 'provider_configs', ['organization_id'])
    op.create_table('organization_ai_settings', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('preferred_provider', sa.String(64), nullable=False), sa.Column('preferred_embedding_model', sa.String(128), nullable=False), sa.Column('temperature', sa.Float(), nullable=False), sa.Column('max_tokens', sa.Integer(), nullable=False), sa.Column('top_p', sa.Float(), nullable=False), sa.Column('frequency_penalty', sa.Float(), nullable=False), sa.Column('presence_penalty', sa.Float(), nullable=False), sa.Column('system_prompt', sa.Text(), nullable=True), sa.Column('citation_mode', sa.String(32), nullable=False), sa.Column('language_code', sa.String(8), nullable=False), sa.Column('monthly_budget_usd', sa.Float(), nullable=True), sa.Column('config_json', postgresql.JSONB(), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id', name='pk_organization_ai_settings'), sa.UniqueConstraint('organization_id', name='uq_organization_ai_settings_org'))
    op.create_index('ix_organization_ai_settings_organization_id', 'organization_ai_settings', ['organization_id'])
    op.create_table('retrieval_logs', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('query_text', sa.Text(), nullable=False), sa.Column('expanded_queries_json', postgresql.JSONB(), nullable=True), sa.Column('filters_json', postgresql.JSONB(), nullable=True), sa.Column('candidate_chunk_ids', postgresql.JSONB(), nullable=True), sa.Column('reranked_chunk_ids', postgresql.JSONB(), nullable=True), sa.Column('retrieval_latency_ms', sa.Integer(), nullable=True), sa.Column('embedding_latency_ms', sa.Integer(), nullable=True), sa.Column('llm_latency_ms', sa.Integer(), nullable=True), sa.Column('prompt_tokens', sa.Integer(), nullable=True), sa.Column('completion_tokens', sa.Integer(), nullable=True), sa.Column('estimated_cost_usd', sa.Float(), nullable=True), sa.Column('cache_hit', sa.Boolean(), server_default='false', nullable=False), sa.Column('provider', sa.String(64), nullable=True), sa.Column('tool_usage_json', postgresql.JSONB(), nullable=True), sa.Column('metadata_json', postgresql.JSONB(), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='SET NULL'), sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id', name='pk_retrieval_logs'))
    op.create_index('ix_retrieval_logs_organization_id', 'retrieval_logs', ['organization_id'])
    op.create_index('ix_retrieval_logs_conversation_id', 'retrieval_logs', ['conversation_id'])
    op.create_index('ix_retrieval_logs_created_at', 'retrieval_logs', ['created_at'])
    op.create_table('conversation_feedback', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('rating', sa.Integer(), nullable=False), sa.Column('comment', sa.Text(), nullable=True), sa.Column('feedback_type', sa.String(32), nullable=False), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id', name='pk_conversation_feedback'), sa.UniqueConstraint('message_id', 'user_id', name='uq_conversation_feedback_message_user'))
    op.create_index('ix_conversation_feedback_organization_id', 'conversation_feedback', ['organization_id'])
    op.create_table('evaluation_runs', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('name', sa.String(255), nullable=False), sa.Column('status', sa.String(32), nullable=False), sa.Column('dataset_json', postgresql.JSONB(), nullable=True), sa.Column('metrics_json', postgresql.JSONB(), nullable=True), sa.Column('notes', sa.Text(), nullable=True), sa.Column('created_by_user_id', postgresql.UUID(as_uuid=True), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'), sa.PrimaryKeyConstraint('id', name='pk_evaluation_runs'))
    op.create_index('ix_evaluation_runs_organization_id', 'evaluation_runs', ['organization_id'])
    op.create_table('saved_searches', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('owner_user_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('name', sa.String(255), nullable=False), sa.Column('query_text', sa.Text(), nullable=False), sa.Column('filters_json', postgresql.JSONB(), nullable=True), sa.Column('search_mode', sa.String(32), nullable=False), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id', name='pk_saved_searches'), sa.UniqueConstraint('organization_id', 'owner_user_id', 'name', name='uq_saved_searches_owner_name'))
    op.create_index('ix_saved_searches_organization_id', 'saved_searches', ['organization_id'])
    op.create_table('ai_memories', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False), sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=True), sa.Column('scope', sa.String(32), nullable=False), sa.Column('key', sa.String(128), nullable=False), sa.Column('value_json', postgresql.JSONB(), nullable=False), sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True), *ts, sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'), sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'), sa.PrimaryKeyConstraint('id', name='pk_ai_memories'))
    op.create_index('ix_ai_memories_organization_id', 'ai_memories', ['organization_id'])
    op.create_index('ix_ai_memories_user_id', 'ai_memories', ['user_id'])
    op.create_index('ix_ai_memories_scope', 'ai_memories', ['scope'])

def downgrade() -> None:
    for table in ('ai_memories', 'saved_searches', 'evaluation_runs', 'conversation_feedback', 'retrieval_logs', 'organization_ai_settings', 'provider_configs', 'prompt_templates', 'chat_messages', 'chat_conversations', 'chat_folders', 'knowledge_embeddings', 'knowledge_chunks', 'knowledge_document_versions', 'knowledge_documents'):
        op.drop_table(table)
