"""Official CBAM SEE export constants (template identity, capacities, blocking codes)."""

from __future__ import annotations

from typing import Final

TEMPLATE_FILENAME: Final[str] = (
    "CBAM SEE V2.1_Example Steel 3 Screws and nuts_final Dosyasının Kopyası- (1) (1).xlsx"
)
TEMPLATE_SHA256: Final[str] = "83170fde547c418dcae7f6a32852555d6874e092769f387b263108a231b2dd64"
TEMPLATE_VERSION: Final[str] = "CBAM_SEE_V2.1"
TEMPLATE_CODE: Final[str] = "OFFICIAL_CBAM_SEE_V2_1"
MAPPING_VERSION: Final[str] = "official-see-mapping-v1"

# Capacity limits (fail-closed; never silently truncate).
CAPACITY_INSTALLATIONS: Final[int] = 1
CAPACITY_GOODS: Final[int] = 10
CAPACITY_PROCESSES: Final[int] = 10
CAPACITY_PRECURSORS: Final[int] = 20
CAPACITY_PROCESS_PRODUCT_USE_ROWS: Final[int] = 9
CAPACITY_PRECURSOR_PRODUCT_USE_ROWS: Final[int] = 10
# B_EmInst section (a) combustion activity rows C17.. where C is int (inspected = 75).
CAPACITY_FUEL_ACTIVITIES: Final[int] = 75

PROCESS_STRIDE: Final[int] = 65
PROCESS_BASE_ROW: Final[int] = 11
PRECURSOR_STRIDE: Final[int] = 44
PRECURSOR_BASE_ROW: Final[int] = 14

EXAMPLE_IDENTIFIERS: Final[tuple[str, ...]] = (
    "Ürün 1",
    "Ürün 2",
    "Ürün 3",
    "Ham madde 1",
    "Ham madde 2",
    "Ham madde 3",
    "Ham madde 4",
    "Firma",
    "Screws",
    "screws",
    "nuts",
    "Galvanized steel-TM2023-158",
    "Galvanized steel-TM2023-148",
)

# Stable readiness / generation blocking codes.
CODE_ORG_BINDING_INVALID: Final[str] = "ORG_BINDING_INVALID"
CODE_PRODUCT_PROFILES_NOT_READY: Final[str] = "PRODUCT_PROFILES_NOT_READY"
CODE_PRODUCTION_PROFILE_LINK_NOT_READY: Final[str] = "PRODUCTION_PROFILE_LINK_NOT_READY"
CODE_DEA_MISSING_OR_STALE: Final[str] = "DEA_MISSING_OR_STALE"
CODE_IEA_MISSING_OR_STALE: Final[str] = "IEA_MISSING_OR_STALE"
CODE_MONTHLY_PRODUCTION_BASIS_NOT_READY: Final[str] = "MONTHLY_PRODUCTION_BASIS_NOT_READY"
CODE_DEA_NOT_BALANCED: Final[str] = "DEA_NOT_BALANCED"
CODE_IEA_NOT_BALANCED: Final[str] = "IEA_NOT_BALANCED"
CODE_PROCESSES_NOT_READY: Final[str] = "PROCESSES_NOT_READY"
CODE_PRECURSORS_NOT_READY_OR_UNBALANCED: Final[str] = "PRECURSORS_NOT_READY_OR_UNBALANCED"
CODE_PEE_V2_MISSING_OR_STALE: Final[str] = "PEE_V2_MISSING_OR_STALE"
CODE_INTERNAL_FLOW_INVALID: Final[str] = "INTERNAL_FLOW_INVALID"
CODE_CAPACITY_EXCEEDED_GOODS: Final[str] = "CAPACITY_EXCEEDED_GOODS"
CODE_CAPACITY_EXCEEDED_PROCESSES: Final[str] = "CAPACITY_EXCEEDED_PROCESSES"
CODE_CAPACITY_EXCEEDED_PRECURSORS: Final[str] = "CAPACITY_EXCEEDED_PRECURSORS"
CODE_CAPACITY_EXCEEDED_PROCESS_USES: Final[str] = "CAPACITY_EXCEEDED_PROCESS_USES"
CODE_CAPACITY_EXCEEDED_PRECURSOR_USES: Final[str] = "CAPACITY_EXCEEDED_PRECURSOR_USES"
CODE_CAPACITY_EXCEEDED_FUELS: Final[str] = "CAPACITY_EXCEEDED_FUELS"
CODE_CAPACITY_EXCEEDED_INSTALLATIONS: Final[str] = "CAPACITY_EXCEEDED_INSTALLATIONS"
CODE_MAPPING_OR_TEMPLATE_INVALID: Final[str] = "MAPPING_OR_TEMPLATE_INVALID"
CODE_RECALCULATION_ENGINE_UNAVAILABLE: Final[str] = "RECALCULATION_ENGINE_UNAVAILABLE"
CODE_EXAMPLE_LEAKAGE: Final[str] = "EXAMPLE_LEAKAGE_DETECTED"
CODE_FORMULA_PRESERVATION_FAILED: Final[str] = "FORMULA_PRESERVATION_FAILED"
CODE_FORMULA_PARITY_FAILED: Final[str] = "FORMULA_PARITY_FAILED"
CODE_IDEMPOTENCY_KEY_REUSED: Final[str] = "IDEMPOTENCY_KEY_REUSED"

GENERATION_STATUS_PENDING: Final[str] = "PENDING"
GENERATION_STATUS_RUNNING: Final[str] = "RUNNING"
GENERATION_STATUS_COMPLETED: Final[str] = "COMPLETED"
GENERATION_STATUS_FAILED: Final[str] = "FAILED"

VALIDATION_STATUS_PENDING: Final[str] = "PENDING"
VALIDATION_STATUS_PASSED: Final[str] = "PASSED"
VALIDATION_STATUS_FAILED: Final[str] = "FAILED"
VALIDATION_STATUS_SKIPPED: Final[str] = "SKIPPED"

PARITY_STATUS_PENDING: Final[str] = "PENDING"
PARITY_STATUS_PASSED: Final[str] = "PASSED"
PARITY_STATUS_FAILED: Final[str] = "FAILED"
PARITY_STATUS_ENGINE_UNAVAILABLE: Final[str] = "ENGINE_UNAVAILABLE"

XLSX_MIME: Final[str] = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"

UNSUPPORTED_METHODS: Final[tuple[str, ...]] = (
    "PROCESS_EMISSIONS",
    "MASS_BALANCE",
)
UNSUPPORTED_MONITORING_APPROACHES: Final[tuple[str, ...]] = (
    "Process emissions",
    "Mass Balance",
)

LOCAL_REFERENCE_RELATIVE: Final[str] = (
    "local-reference/CBAM SEE V2.1_Example Steel 3 Screws and nuts_final "
    "Dosyasının Kopyası- (1) (1).xlsx"
)
