from __future__ import annotations
import uuid
from datetime import date, datetime
from decimal import Decimal
from typing import Any
from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Index, Integer, Numeric, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column
from ecotrace.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

class AgentDefinition(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'agent_definitions'
    __table_args__ = (UniqueConstraint('code', name='uq_agent_definitions_code'),)
    code: Mapped[str] = mapped_column(String(64), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    allowed_tools_json: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    required_permissions_json: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    max_execution_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=120)
    max_tool_calls: Mapped[int] = mapped_column(Integer, nullable=False, default=12)
    max_token_usage: Mapped[int] = mapped_column(Integer, nullable=False, default=2000)
    approval_policy: Mapped[str] = mapped_column(String(32), nullable=False, default='write_only')
    output_schema_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    is_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

class AgentTool(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'agent_tools'
    __table_args__ = (UniqueConstraint('tool_code', name='uq_agent_tools_code'),)
    tool_code: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    input_schema_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    output_schema_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    required_permission: Mapped[str] = mapped_column(String(64), nullable=False, default='ai_read')
    organization_scoped: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    write_classification: Mapped[str] = mapped_column(String(16), nullable=False, default='read')
    approval_required: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    audit_policy: Mapped[str] = mapped_column(String(32), nullable=False, default='always')
    timeout_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=30)
    is_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

class AgentExecution(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'agent_executions'
    __table_args__ = (Index('ix_agent_executions_organization_id', 'organization_id'), Index('ix_agent_executions_agent_code', 'agent_code'), Index('ix_agent_executions_status', 'status'), Index('ix_agent_executions_created_at', 'created_at'), Index('ix_agent_executions_trace_id', 'trace_id'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    agent_code: Mapped[str] = mapped_column(String(64), nullable=False)
    conversation_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    trigger_type: Mapped[str] = mapped_column(String(32), nullable=False, default='manual')
    trigger_reference_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='queued')
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    triggered_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    model_provider: Mapped[str | None] = mapped_column(String(64), nullable=True)
    model_name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    prompt_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    completion_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    estimated_cost: Mapped[Decimal | None] = mapped_column(Numeric(18, 8), nullable=True)
    tool_call_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    result_summary_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    error_details_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)

class AgentToolCall(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'agent_tool_calls'
    __table_args__ = (Index('ix_agent_tool_calls_execution_id', 'agent_execution_id'),)
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    agent_execution_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('agent_executions.id', ondelete='CASCADE'), nullable=False)
    tool_code: Mapped[str] = mapped_column(String(128), nullable=False)
    input_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    output_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='completed')
    duration_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

class AgentActionRequest(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'agent_action_requests'
    __table_args__ = (Index('ix_agent_action_requests_organization_id', 'organization_id'), Index('ix_agent_action_requests_status', 'status'), Index('ix_agent_action_requests_risk_level', 'risk_level'), Index('ix_agent_action_requests_created_at', 'created_at'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    agent_execution_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('agent_executions.id', ondelete='SET NULL'), nullable=True)
    action_type: Mapped[str] = mapped_column(String(64), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    input_payload_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    proposed_changes_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    risk_level: Mapped[str] = mapped_column(String(16), nullable=False, default='medium')
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='pending')
    requested_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    reviewed_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    review_comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rejected_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    executed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    execution_result_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

class AutomationRule(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'automation_rules'
    __table_args__ = (UniqueConstraint('organization_id', 'code', name='uq_automation_rules_org_code'), Index('ix_automation_rules_organization_id', 'organization_id'), Index('ix_automation_rules_status', 'status'), Index('ix_automation_rules_trigger_type', 'trigger_type'), Index('ix_automation_rules_next_run_at', 'next_run_at'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    code: Mapped[str] = mapped_column(String(64), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    trigger_type: Mapped[str] = mapped_column(String(64), nullable=False)
    trigger_config_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    condition_config_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    action_type: Mapped[str] = mapped_column(String(64), nullable=False)
    action_config_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    approval_required: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='draft')
    timezone: Mapped[str] = mapped_column(String(64), nullable=False, default='UTC')
    last_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    next_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_execution_key: Mapped[str | None] = mapped_column(String(128), nullable=True)
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    approved_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)

class AutomationRuleExecution(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'automation_rule_executions'
    __table_args__ = (UniqueConstraint('organization_id', 'execution_key', name='uq_automation_exec_key'), Index('ix_automation_rule_executions_rule_id', 'automation_rule_id'), Index('ix_automation_rule_executions_status', 'status'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    automation_rule_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('automation_rules.id', ondelete='CASCADE'), nullable=False)
    execution_key: Mapped[str] = mapped_column(String(128), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='running')
    result_summary_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    error_details_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

class ScheduledJob(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'scheduled_jobs'
    __table_args__ = (UniqueConstraint('organization_id', 'job_key', name='uq_scheduled_jobs_org_key'), Index('ix_scheduled_jobs_next_run_at', 'next_run_at'), Index('ix_scheduled_jobs_status', 'status'))
    organization_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=True)
    job_key: Mapped[str] = mapped_column(String(128), nullable=False)
    job_type: Mapped[str] = mapped_column(String(64), nullable=False)
    schedule_expression: Mapped[str] = mapped_column(String(128), nullable=False)
    timezone: Mapped[str] = mapped_column(String(64), nullable=False, default='UTC')
    payload_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='active')
    allow_concurrent: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    next_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_run_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

class JobExecution(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'job_executions'
    __table_args__ = (UniqueConstraint('organization_id', 'execution_key', name='uq_job_executions_org_key'), Index('ix_job_executions_organization_id', 'organization_id'), Index('ix_job_executions_job_type', 'job_type'), Index('ix_job_executions_status', 'status'), Index('ix_job_executions_scheduled_for', 'scheduled_for'), Index('ix_job_executions_execution_key', 'execution_key'))
    organization_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=True)
    job_type: Mapped[str] = mapped_column(String(64), nullable=False)
    job_reference_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    execution_key: Mapped[str] = mapped_column(String(128), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='scheduled')
    scheduled_for: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    attempt_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=3)
    worker_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    result_summary_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    error_details_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    trace_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    locked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

class AnomalyDetectionRule(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'anomaly_detection_rules'
    __table_args__ = (UniqueConstraint('organization_id', 'code', name='uq_anomaly_rules_org_code'), Index('ix_anomaly_detection_rules_organization_id', 'organization_id'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    code: Mapped[str] = mapped_column(String(64), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    metric_type: Mapped[str] = mapped_column(String(64), nullable=False)
    detection_method: Mapped[str] = mapped_column(String(64), nullable=False)
    threshold_config_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    scope_config_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    severity_mapping_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    minimum_data_points: Mapped[int] = mapped_column(Integer, nullable=False, default=5)
    lookback_period: Mapped[int] = mapped_column(Integer, nullable=False, default=12)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

class AnomalyEvent(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'anomaly_events'
    __table_args__ = (UniqueConstraint('organization_id', 'fingerprint', name='uq_anomaly_events_fingerprint'), Index('ix_anomaly_events_organization_id', 'organization_id'), Index('ix_anomaly_events_severity', 'severity'), Index('ix_anomaly_events_status', 'status'), Index('ix_anomaly_events_detected_at', 'detected_at'), Index('ix_anomaly_events_facility_id', 'facility_id'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    rule_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('anomaly_detection_rules.id', ondelete='SET NULL'), nullable=True)
    fingerprint: Mapped[str] = mapped_column(String(128), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    metric_code: Mapped[str] = mapped_column(String(64), nullable=False)
    observed_value: Mapped[Decimal | None] = mapped_column(Numeric(24, 8), nullable=True)
    expected_value: Mapped[Decimal | None] = mapped_column(Numeric(24, 8), nullable=True)
    deviation_value: Mapped[Decimal | None] = mapped_column(Numeric(24, 8), nullable=True)
    deviation_percentage: Mapped[Decimal | None] = mapped_column(Numeric(18, 8), nullable=True)
    anomaly_score: Mapped[Decimal | None] = mapped_column(Numeric(18, 8), nullable=True)
    severity: Mapped[str] = mapped_column(String(16), nullable=False, default='medium')
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='open')
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    reporting_period_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    facility_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    activity_type_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    inventory_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    evidence_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    assigned_to_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolution_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

class ForecastDefinition(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'forecast_definitions'
    __table_args__ = (UniqueConstraint('organization_id', 'code', name='uq_forecast_definitions_org_code'), Index('ix_forecast_definitions_organization_id', 'organization_id'), Index('ix_forecast_definitions_metric_type', 'metric_type'), Index('ix_forecast_definitions_is_active', 'is_active'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    code: Mapped[str] = mapped_column(String(64), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    metric_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False, default='organization')
    entity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    method: Mapped[str] = mapped_column(String(64), nullable=False, default='linear_trend')
    historical_period_count: Mapped[int] = mapped_column(Integer, nullable=False, default=12)
    forecast_horizon: Mapped[int] = mapped_column(Integer, nullable=False, default=6)
    granularity: Mapped[str] = mapped_column(String(16), nullable=False, default='monthly')
    confidence_level: Mapped[Decimal] = mapped_column(Numeric(8, 4), nullable=False, default=Decimal('0.8'))
    configuration_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

class ForecastRun(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'forecast_runs'
    __table_args__ = (Index('ix_forecast_runs_organization_id', 'organization_id'), Index('ix_forecast_runs_definition_id', 'forecast_definition_id'), Index('ix_forecast_runs_status', 'status'), Index('ix_forecast_runs_generated_at', 'generated_at'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    forecast_definition_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('forecast_definitions.id', ondelete='CASCADE'), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='completed')
    training_start_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    training_end_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    forecast_start_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    forecast_end_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    model_version: Mapped[str] = mapped_column(String(64), nullable=False, default='ecotrace-forecast-0.7.1')
    data_point_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    accuracy_metrics_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    source_data_quality: Mapped[str] = mapped_column(String(32), nullable=False, default='provisional')
    generated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    triggered_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    error_details_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    disclaimer: Mapped[str] = mapped_column(Text, nullable=False, default='Model-based estimate only. Not a guarantee.')

class ForecastPoint(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'forecast_points'
    __table_args__ = (Index('ix_forecast_points_run_id', 'forecast_run_id'),)
    forecast_run_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('forecast_runs.id', ondelete='CASCADE'), nullable=False)
    period_start: Mapped[date] = mapped_column(Date, nullable=False)
    period_end: Mapped[date] = mapped_column(Date, nullable=False)
    predicted_value: Mapped[Decimal] = mapped_column(Numeric(24, 8), nullable=False)
    lower_bound: Mapped[Decimal | None] = mapped_column(Numeric(24, 8), nullable=True)
    upper_bound: Mapped[Decimal | None] = mapped_column(Numeric(24, 8), nullable=True)
    actual_value: Mapped[Decimal | None] = mapped_column(Numeric(24, 8), nullable=True)

class DataQualityRule(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'data_quality_rules'
    __table_args__ = (UniqueConstraint('organization_id', 'code', name='uq_data_quality_rules_org_code'),)
    organization_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=True)
    code: Mapped[str] = mapped_column(String(64), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    issue_type: Mapped[str] = mapped_column(String(64), nullable=False)
    severity_default: Mapped[str] = mapped_column(String(16), nullable=False, default='medium')
    config_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

class DataQualityIssue(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'data_quality_issues'
    __table_args__ = (UniqueConstraint('organization_id', 'fingerprint', name='uq_dq_issues_fingerprint'), Index('ix_data_quality_issues_organization_id', 'organization_id'), Index('ix_data_quality_issues_issue_type', 'issue_type'), Index('ix_data_quality_issues_severity', 'severity'), Index('ix_data_quality_issues_status', 'status'), Index('ix_data_quality_issues_detected_at', 'detected_at'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    fingerprint: Mapped[str] = mapped_column(String(128), nullable=False)
    issue_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    severity: Mapped[str] = mapped_column(String(16), nullable=False, default='medium')
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    evidence_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='open')
    detected_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    assigned_to_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolution_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

class Alert(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'alerts'
    __table_args__ = (UniqueConstraint('organization_id', 'fingerprint', name='uq_alerts_fingerprint'), Index('ix_alerts_organization_id', 'organization_id'), Index('ix_alerts_alert_type', 'alert_type'), Index('ix_alerts_severity', 'severity'), Index('ix_alerts_status', 'status'), Index('ix_alerts_created_at', 'created_at'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    fingerprint: Mapped[str] = mapped_column(String(128), nullable=False)
    alert_type: Mapped[str] = mapped_column(String(64), nullable=False)
    source_type: Mapped[str] = mapped_column(String(64), nullable=False)
    source_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[str] = mapped_column(String(16), nullable=False, default='medium')
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='open')
    evidence_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    assigned_to_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    created_by_system: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    acknowledged_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolution_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

class NotificationPreference(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'notification_preferences'
    __table_args__ = (UniqueConstraint('user_id', 'organization_id', 'notification_type', name='uq_notification_prefs'),)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='CASCADE'), nullable=False)
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    notification_type: Mapped[str] = mapped_column(String(64), nullable=False)
    in_app_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    email_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    minimum_severity: Mapped[str] = mapped_column(String(16), nullable=False, default='low')
    digest_frequency: Mapped[str] = mapped_column(String(32), nullable=False, default='realtime')
    quiet_hours_start: Mapped[str | None] = mapped_column(String(8), nullable=True)
    quiet_hours_end: Mapped[str | None] = mapped_column(String(8), nullable=True)
    timezone: Mapped[str] = mapped_column(String(64), nullable=False, default='UTC')

class Notification(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'notifications'
    __table_args__ = (Index('ix_notifications_user_id', 'user_id'), Index('ix_notifications_organization_id', 'organization_id'), Index('ix_notifications_status', 'status'), Index('ix_notifications_created_at', 'created_at'))
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='CASCADE'), nullable=False)
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    notification_type: Mapped[str] = mapped_column(String(64), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    action_url: Mapped[str | None] = mapped_column(String(512), nullable=True)
    severity: Mapped[str] = mapped_column(String(16), nullable=False, default='info')
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='pending')
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

class ScheduledReport(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'scheduled_reports'
    __table_args__ = (UniqueConstraint('organization_id', 'code', name='uq_scheduled_reports_org_code'), Index('ix_scheduled_reports_organization_id', 'organization_id'), Index('ix_scheduled_reports_status', 'status'), Index('ix_scheduled_reports_next_generation_at', 'next_generation_at'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    code: Mapped[str] = mapped_column(String(64), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    report_type: Mapped[str] = mapped_column(String(64), nullable=False)
    schedule_expression: Mapped[str] = mapped_column(String(128), nullable=False)
    timezone: Mapped[str] = mapped_column(String(64), nullable=False, default='UTC')
    report_config_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    output_format: Mapped[str] = mapped_column(String(16), nullable=False, default='json')
    recipient_user_ids_json: Mapped[list[str] | None] = mapped_column(JSONB, nullable=True)
    approval_required: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='draft')
    last_generated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    next_generation_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)

class GeneratedReport(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'generated_reports'
    __table_args__ = (Index('ix_generated_reports_organization_id', 'organization_id'), Index('ix_generated_reports_report_type', 'report_type'), Index('ix_generated_reports_status', 'status'), Index('ix_generated_reports_created_at', 'created_at'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    scheduled_report_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('scheduled_reports.id', ondelete='SET NULL'), nullable=True)
    report_type: Mapped[str] = mapped_column(String(64), nullable=False)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    reporting_period_start: Mapped[date | None] = mapped_column(Date, nullable=True)
    reporting_period_end: Mapped[date | None] = mapped_column(Date, nullable=True)
    output_format: Mapped[str] = mapped_column(String(16), nullable=False, default='json')
    storage_path: Mapped[str] = mapped_column(String(1024), nullable=False)
    checksum: Mapped[str] = mapped_column(String(64), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='ready')
    generated_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    generated_by_job_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    approved_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    content_preview_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

class SupplierMonitoringProfile(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'supplier_monitoring_profiles'
    __table_args__ = (UniqueConstraint('organization_id', 'supplier_id', name='uq_supplier_monitoring_org_supplier'), Index('ix_supplier_monitoring_profiles_organization_id', 'organization_id'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    supplier_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('suppliers.id', ondelete='CASCADE'), nullable=False)
    monitoring_status: Mapped[str] = mapped_column(String(32), nullable=False, default='active')
    risk_level: Mapped[str] = mapped_column(String(16), nullable=False, default='medium')
    required_document_types_json: Mapped[list[str] | None] = mapped_column(JSONB, nullable=True)
    review_frequency: Mapped[str] = mapped_column(String(32), nullable=False, default='quarterly')
    last_reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    next_review_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    assigned_to_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)

class SupplierAssessment(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'supplier_assessments'
    __table_args__ = (Index('ix_supplier_assessments_organization_id', 'organization_id'), Index('ix_supplier_assessments_supplier_id', 'supplier_id'), Index('ix_supplier_assessments_assessment_date', 'assessment_date'), Index('ix_supplier_assessments_risk_level', 'risk_level'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    supplier_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('suppliers.id', ondelete='CASCADE'), nullable=False)
    assessment_date: Mapped[date] = mapped_column(Date, nullable=False)
    assessment_type: Mapped[str] = mapped_column(String(64), nullable=False, default='internal')
    emissions_score: Mapped[Decimal | None] = mapped_column(Numeric(8, 4), nullable=True)
    data_quality_score: Mapped[Decimal | None] = mapped_column(Numeric(8, 4), nullable=True)
    document_completeness_score: Mapped[Decimal | None] = mapped_column(Numeric(8, 4), nullable=True)
    sustainability_score: Mapped[Decimal | None] = mapped_column(Numeric(8, 4), nullable=True)
    risk_level: Mapped[str] = mapped_column(String(16), nullable=False, default='medium')
    findings_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    recommendations_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    assessed_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='completed')
    disclaimer: Mapped[str] = mapped_column(Text, nullable=False, default='Internal non-certified assessment for decision support only.')

class RegulatoryDocument(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'regulatory_documents'
    __table_args__ = (UniqueConstraint('jurisdiction_code', 'regulation_code', 'version', name='uq_reg_doc_ver'), Index('ix_regulatory_documents_jurisdiction_code', 'jurisdiction_code'), Index('ix_regulatory_documents_regulation_code', 'regulation_code'), Index('ix_regulatory_documents_category', 'category'), Index('ix_regulatory_documents_effective_from', 'effective_from'), Index('ix_regulatory_documents_status', 'status'))
    jurisdiction_code: Mapped[str] = mapped_column(String(16), nullable=False)
    authority_name: Mapped[str] = mapped_column(String(255), nullable=False)
    regulation_code: Mapped[str] = mapped_column(String(128), nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    category: Mapped[str] = mapped_column(String(64), nullable=False, default='climate')
    source_url: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    published_at: Mapped[date | None] = mapped_column(Date, nullable=True)
    effective_from: Mapped[date | None] = mapped_column(Date, nullable=True)
    effective_to: Mapped[date | None] = mapped_column(Date, nullable=True)
    version: Mapped[str] = mapped_column(String(32), nullable=False, default='1')
    status: Mapped[str] = mapped_column(String(32), nullable=False, default='active')
    document_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    is_demo: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    applicability_tags_json: Mapped[list[str] | None] = mapped_column(JSONB, nullable=True)

class OrganizationRegulatoryAssessment(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    __tablename__ = 'organization_regulatory_assessments'
    __table_args__ = (UniqueConstraint('organization_id', 'regulatory_document_id', name='uq_org_reg_assessment'), Index('ix_org_reg_assessments_organization_id', 'organization_id'), Index('ix_org_reg_assessments_applicability_status', 'applicability_status'), Index('ix_org_reg_assessments_review_status', 'review_status'), Index('ix_org_reg_assessments_due_date', 'due_date'))
    organization_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False)
    regulatory_document_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey('regulatory_documents.id', ondelete='CASCADE'), nullable=False)
    applicability_status: Mapped[str] = mapped_column(String(32), nullable=False, default='unknown')
    relevance_score: Mapped[Decimal | None] = mapped_column(Numeric(8, 4), nullable=True)
    review_status: Mapped[str] = mapped_column(String(32), nullable=False, default='pending')
    assigned_to_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), nullable=True)
    assessment_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    impact_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    action_required: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    due_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    citations_json: Mapped[list[dict[str, Any]] | None] = mapped_column(JSONB, nullable=True)
